{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='rollout', url='', help='"Rollout is the Schema for the Rollout API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Rollout', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'standard.oam.dev/v1alpha1',
    kind: 'Rollout',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"RolloutSpec defines how to describe an update between different compRevision"'),
  spec: {
    '#rolloutPlan':: d.obj(help='"RolloutPlan is the details on how to rollout the resources"'),
    rolloutPlan: {
      '#canaryMetric':: d.obj(help='"CanaryMetric provides a way for the rollout process to automatically check certain metrics before complete the process"'),
      canaryMetric: {
        '#metricsRange':: d.obj(help='"Range value accepted for this metric"'),
        metricsRange: {
          '#withMax':: d.fn(help='"Maximum value"', args=[d.arg(name='max', type=d.T.any)]),
          withMax(max): { metricsRange+: { max: max } },
          '#withMin':: d.fn(help='"Minimum value"', args=[d.arg(name='min', type=d.T.any)]),
          withMin(min): { metricsRange+: { min: min } },
        },
        '#templateRef':: d.obj(help='"TemplateRef references a metric template object"'),
        templateRef: {
          '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
          withApiVersion(apiVersion): { templateRef+: { apiVersion: apiVersion } },
          '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
          withFieldPath(fieldPath): { templateRef+: { fieldPath: fieldPath } },
          '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { templateRef+: { kind: kind } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { templateRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { templateRef+: { namespace: namespace } },
          '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
          withResourceVersion(resourceVersion): { templateRef+: { resourceVersion: resourceVersion } },
          '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
          withUid(uid): { templateRef+: { uid: uid } },
        },
        '#withInterval':: d.fn(help='"Interval represents the windows size"', args=[d.arg(name='interval', type=d.T.string)]),
        withInterval(interval): { interval: interval },
        '#withName':: d.fn(help='"Name of the metric"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#rolloutBatches':: d.obj(help="\"The exact distribution among batches. its size has to be exactly the same as the NumBatches (if set) The total number cannot exceed the targetSize or the size of the source resource We will IGNORE the last batch's replica field if it's a percentage since round errors can lead to inaccurate sum We highly recommend to leave the last batch's replica field empty\""),
      rolloutBatches: {
        '#batchRolloutWebhooks':: d.obj(help='"RolloutWebhooks provides a way for the batch rollout to interact with an external process"'),
        batchRolloutWebhooks: {
          '#withExpectedStatus':: d.fn(help='"ExpectedStatus contains all the expected http status code that we will accept as success"', args=[d.arg(name='expectedStatus', type=d.T.array)]),
          withExpectedStatus(expectedStatus): { expectedStatus: if std.isArray(v=expectedStatus) then expectedStatus else [expectedStatus] },
          '#withExpectedStatusMixin':: d.fn(help='"ExpectedStatus contains all the expected http status code that we will accept as success"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='expectedStatus', type=d.T.array)]),
          withExpectedStatusMixin(expectedStatus): { expectedStatus+: if std.isArray(v=expectedStatus) then expectedStatus else [expectedStatus] },
          '#withMetadata':: d.fn(help='"Metadata (key-value pairs) for this webhook"', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadata(metadata): { metadata: metadata },
          '#withMetadataMixin':: d.fn(help='"Metadata (key-value pairs) for this webhook"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadataMixin(metadata): { metadata+: metadata },
          '#withMethod':: d.fn(help='"Method the HTTP call method, default is POST"', args=[d.arg(name='method', type=d.T.string)]),
          withMethod(method): { method: method },
          '#withName':: d.fn(help='"Name of this webhook"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withType':: d.fn(help='"Type of this webhook"', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
          '#withUrl':: d.fn(help='"URL address of this webhook"', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { url: url },
        },
        '#canaryMetric':: d.obj(help='"CanaryMetric provides a way for the batch rollout process to automatically check certain metrics before moving to the next batch"'),
        canaryMetric: {
          '#metricsRange':: d.obj(help='"Range value accepted for this metric"'),
          metricsRange: {
            '#withMax':: d.fn(help='"Maximum value"', args=[d.arg(name='max', type=d.T.any)]),
            withMax(max): { metricsRange+: { max: max } },
            '#withMin':: d.fn(help='"Minimum value"', args=[d.arg(name='min', type=d.T.any)]),
            withMin(min): { metricsRange+: { min: min } },
          },
          '#templateRef':: d.obj(help='"TemplateRef references a metric template object"'),
          templateRef: {
            '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
            withApiVersion(apiVersion): { templateRef+: { apiVersion: apiVersion } },
            '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
            withFieldPath(fieldPath): { templateRef+: { fieldPath: fieldPath } },
            '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
            withKind(kind): { templateRef+: { kind: kind } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { templateRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { templateRef+: { namespace: namespace } },
            '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
            withResourceVersion(resourceVersion): { templateRef+: { resourceVersion: resourceVersion } },
            '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
            withUid(uid): { templateRef+: { uid: uid } },
          },
          '#withInterval':: d.fn(help='"Interval represents the windows size"', args=[d.arg(name='interval', type=d.T.string)]),
          withInterval(interval): { interval: interval },
          '#withName':: d.fn(help='"Name of the metric"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
        },
        '#withBatchRolloutWebhooks':: d.fn(help='"RolloutWebhooks provides a way for the batch rollout to interact with an external process"', args=[d.arg(name='batchRolloutWebhooks', type=d.T.array)]),
        withBatchRolloutWebhooks(batchRolloutWebhooks): { batchRolloutWebhooks: if std.isArray(v=batchRolloutWebhooks) then batchRolloutWebhooks else [batchRolloutWebhooks] },
        '#withBatchRolloutWebhooksMixin':: d.fn(help='"RolloutWebhooks provides a way for the batch rollout to interact with an external process"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='batchRolloutWebhooks', type=d.T.array)]),
        withBatchRolloutWebhooksMixin(batchRolloutWebhooks): { batchRolloutWebhooks+: if std.isArray(v=batchRolloutWebhooks) then batchRolloutWebhooks else [batchRolloutWebhooks] },
        '#withCanaryMetric':: d.fn(help='"CanaryMetric provides a way for the batch rollout process to automatically check certain metrics before moving to the next batch"', args=[d.arg(name='canaryMetric', type=d.T.array)]),
        withCanaryMetric(canaryMetric): { canaryMetric: if std.isArray(v=canaryMetric) then canaryMetric else [canaryMetric] },
        '#withCanaryMetricMixin':: d.fn(help='"CanaryMetric provides a way for the batch rollout process to automatically check certain metrics before moving to the next batch"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='canaryMetric', type=d.T.array)]),
        withCanaryMetricMixin(canaryMetric): { canaryMetric+: if std.isArray(v=canaryMetric) then canaryMetric else [canaryMetric] },
        '#withInstanceInterval':: d.fn(help='"The wait time, in seconds, between instances upgrades, default = 0"', args=[d.arg(name='instanceInterval', type=d.T.integer)]),
        withInstanceInterval(instanceInterval): { instanceInterval: instanceInterval },
        '#withMaxUnavailable':: d.fn(help='"MaxUnavailable is the max allowed number of pods that is unavailable during the upgrade. We will mark the batch as ready as long as there are less or equal number of pods unavailable than this number. default = 0"', args=[d.arg(name='maxUnavailable', type=d.T.any)]),
        withMaxUnavailable(maxUnavailable): { maxUnavailable: maxUnavailable },
        '#withPodList':: d.fn(help='"The list of Pods to get upgraded it is mutually exclusive with the Replicas field"', args=[d.arg(name='podList', type=d.T.array)]),
        withPodList(podList): { podList: if std.isArray(v=podList) then podList else [podList] },
        '#withPodListMixin':: d.fn(help='"The list of Pods to get upgraded it is mutually exclusive with the Replicas field"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='podList', type=d.T.array)]),
        withPodListMixin(podList): { podList+: if std.isArray(v=podList) then podList else [podList] },
        '#withReplicas':: d.fn(help='"Replicas is the number of pods to upgrade in this batch it can be an absolute number (ex: 5) or a percentage of total pods we will ignore the percentage of the last batch to just fill the gap it is mutually exclusive with the PodList field"', args=[d.arg(name='replicas', type=d.T.any)]),
        withReplicas(replicas): { replicas: replicas },
      },
      '#rolloutWebhooks':: d.obj(help='"RolloutWebhooks provide a way for the rollout to interact with an external process"'),
      rolloutWebhooks: {
        '#withExpectedStatus':: d.fn(help='"ExpectedStatus contains all the expected http status code that we will accept as success"', args=[d.arg(name='expectedStatus', type=d.T.array)]),
        withExpectedStatus(expectedStatus): { expectedStatus: if std.isArray(v=expectedStatus) then expectedStatus else [expectedStatus] },
        '#withExpectedStatusMixin':: d.fn(help='"ExpectedStatus contains all the expected http status code that we will accept as success"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='expectedStatus', type=d.T.array)]),
        withExpectedStatusMixin(expectedStatus): { expectedStatus+: if std.isArray(v=expectedStatus) then expectedStatus else [expectedStatus] },
        '#withMetadata':: d.fn(help='"Metadata (key-value pairs) for this webhook"', args=[d.arg(name='metadata', type=d.T.object)]),
        withMetadata(metadata): { metadata: metadata },
        '#withMetadataMixin':: d.fn(help='"Metadata (key-value pairs) for this webhook"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
        withMetadataMixin(metadata): { metadata+: metadata },
        '#withMethod':: d.fn(help='"Method the HTTP call method, default is POST"', args=[d.arg(name='method', type=d.T.string)]),
        withMethod(method): { method: method },
        '#withName':: d.fn(help='"Name of this webhook"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withType':: d.fn(help='"Type of this webhook"', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
        '#withUrl':: d.fn(help='"URL address of this webhook"', args=[d.arg(name='url', type=d.T.string)]),
        withUrl(url): { url: url },
      },
      '#withBatchPartition':: d.fn(help='"All pods in the batches up to the batchPartition (included) will have the target resource specification while the rest still have the source resource This is designed for the operators to manually rollout Default is the the number of batches which will rollout all the batches"', args=[d.arg(name='batchPartition', type=d.T.integer)]),
      withBatchPartition(batchPartition): { spec+: { rolloutPlan+: { batchPartition: batchPartition } } },
      '#withCanaryMetric':: d.fn(help='"CanaryMetric provides a way for the rollout process to automatically check certain metrics before complete the process"', args=[d.arg(name='canaryMetric', type=d.T.array)]),
      withCanaryMetric(canaryMetric): { spec+: { rolloutPlan+: { canaryMetric: if std.isArray(v=canaryMetric) then canaryMetric else [canaryMetric] } } },
      '#withCanaryMetricMixin':: d.fn(help='"CanaryMetric provides a way for the rollout process to automatically check certain metrics before complete the process"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='canaryMetric', type=d.T.array)]),
      withCanaryMetricMixin(canaryMetric): { spec+: { rolloutPlan+: { canaryMetric+: if std.isArray(v=canaryMetric) then canaryMetric else [canaryMetric] } } },
      '#withNumBatches':: d.fn(help='"The number of batches, default = 1"', args=[d.arg(name='numBatches', type=d.T.integer)]),
      withNumBatches(numBatches): { spec+: { rolloutPlan+: { numBatches: numBatches } } },
      '#withPaused':: d.fn(help='"Paused the rollout, default is false"', args=[d.arg(name='paused', type=d.T.boolean)]),
      withPaused(paused): { spec+: { rolloutPlan+: { paused: paused } } },
      '#withRolloutBatches':: d.fn(help="\"The exact distribution among batches. its size has to be exactly the same as the NumBatches (if set) The total number cannot exceed the targetSize or the size of the source resource We will IGNORE the last batch's replica field if it's a percentage since round errors can lead to inaccurate sum We highly recommend to leave the last batch's replica field empty\"", args=[d.arg(name='rolloutBatches', type=d.T.array)]),
      withRolloutBatches(rolloutBatches): { spec+: { rolloutPlan+: { rolloutBatches: if std.isArray(v=rolloutBatches) then rolloutBatches else [rolloutBatches] } } },
      '#withRolloutBatchesMixin':: d.fn(help="\"The exact distribution among batches. its size has to be exactly the same as the NumBatches (if set) The total number cannot exceed the targetSize or the size of the source resource We will IGNORE the last batch's replica field if it's a percentage since round errors can lead to inaccurate sum We highly recommend to leave the last batch's replica field empty\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='rolloutBatches', type=d.T.array)]),
      withRolloutBatchesMixin(rolloutBatches): { spec+: { rolloutPlan+: { rolloutBatches+: if std.isArray(v=rolloutBatches) then rolloutBatches else [rolloutBatches] } } },
      '#withRolloutStrategy':: d.fn(help='"RolloutStrategy defines strategies for the rollout plan The default is IncreaseFirstRolloutStrategyType"', args=[d.arg(name='rolloutStrategy', type=d.T.string)]),
      withRolloutStrategy(rolloutStrategy): { spec+: { rolloutPlan+: { rolloutStrategy: rolloutStrategy } } },
      '#withRolloutWebhooks':: d.fn(help='"RolloutWebhooks provide a way for the rollout to interact with an external process"', args=[d.arg(name='rolloutWebhooks', type=d.T.array)]),
      withRolloutWebhooks(rolloutWebhooks): { spec+: { rolloutPlan+: { rolloutWebhooks: if std.isArray(v=rolloutWebhooks) then rolloutWebhooks else [rolloutWebhooks] } } },
      '#withRolloutWebhooksMixin':: d.fn(help='"RolloutWebhooks provide a way for the rollout to interact with an external process"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='rolloutWebhooks', type=d.T.array)]),
      withRolloutWebhooksMixin(rolloutWebhooks): { spec+: { rolloutPlan+: { rolloutWebhooks+: if std.isArray(v=rolloutWebhooks) then rolloutWebhooks else [rolloutWebhooks] } } },
      '#withTargetSize':: d.fn(help='"The size of the target resource. The default is the same as the size of the source resource."', args=[d.arg(name='targetSize', type=d.T.integer)]),
      withTargetSize(targetSize): { spec+: { rolloutPlan+: { targetSize: targetSize } } },
    },
    '#withComponentName':: d.fn(help='"ComponentName specify the component name"', args=[d.arg(name='componentName', type=d.T.string)]),
    withComponentName(componentName): { spec+: { componentName: componentName } },
    '#withSourceRevisionName':: d.fn(help="\"SourceRevisionName contains the name of the componentRevisionName  that we need to upgrade from. it can be empty only when it's the first time to deploy the application\"", args=[d.arg(name='sourceRevisionName', type=d.T.string)]),
    withSourceRevisionName(sourceRevisionName): { spec+: { sourceRevisionName: sourceRevisionName } },
    '#withTargetRevisionName':: d.fn(help='"TargetRevisionName contains the name of the componentRevisionName that we need to upgrade to."', args=[d.arg(name='targetRevisionName', type=d.T.string)]),
    withTargetRevisionName(targetRevisionName): { spec+: { targetRevisionName: targetRevisionName } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
